#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boxa
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BoxaRegistration")]
	public partial class BoxaDiamondRegDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMemberDetail(MemberDetail instance);
    partial void UpdateMemberDetail(MemberDetail instance);
    partial void DeleteMemberDetail(MemberDetail instance);
    partial void InsertMemberReg(MemberReg instance);
    partial void UpdateMemberReg(MemberReg instance);
    partial void DeleteMemberReg(MemberReg instance);
    #endregion
		
		public BoxaDiamondRegDataContext() : 
				base(global::Boxa.Properties.Settings.Default.BoxaRegistrationConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BoxaDiamondRegDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoxaDiamondRegDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoxaDiamondRegDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoxaDiamondRegDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MemberDetail> MemberDetails
		{
			get
			{
				return this.GetTable<MemberDetail>();
			}
		}
		
		public System.Data.Linq.Table<MemberReg> MemberRegs
		{
			get
			{
				return this.GetTable<MemberReg>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MemberDetail")]
	public partial class MemberDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MemberDetailId;
		
		private int _MemberRegId;
		
		private byte _RelationType;
		
		private string _Name;
		
		private System.DateTime _DateofBirth;
		
		private decimal _Amount;
		
		private EntityRef<MemberReg> _MemberReg;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMemberDetailIdChanging(int value);
    partial void OnMemberDetailIdChanged();
    partial void OnMemberRegIdChanging(int value);
    partial void OnMemberRegIdChanged();
    partial void OnRelationTypeChanging(byte value);
    partial void OnRelationTypeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDateofBirthChanging(System.DateTime value);
    partial void OnDateofBirthChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    #endregion
		
		public MemberDetail()
		{
			this._MemberReg = default(EntityRef<MemberReg>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberDetailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MemberDetailId
		{
			get
			{
				return this._MemberDetailId;
			}
			set
			{
				if ((this._MemberDetailId != value))
				{
					this.OnMemberDetailIdChanging(value);
					this.SendPropertyChanging();
					this._MemberDetailId = value;
					this.SendPropertyChanged("MemberDetailId");
					this.OnMemberDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberRegId", DbType="Int NOT NULL")]
		public int MemberRegId
		{
			get
			{
				return this._MemberRegId;
			}
			set
			{
				if ((this._MemberRegId != value))
				{
					if (this._MemberReg.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMemberRegIdChanging(value);
					this.SendPropertyChanging();
					this._MemberRegId = value;
					this.SendPropertyChanged("MemberRegId");
					this.OnMemberRegIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationType", DbType="TinyInt NOT NULL")]
		public byte RelationType
		{
			get
			{
				return this._RelationType;
			}
			set
			{
				if ((this._RelationType != value))
				{
					this.OnRelationTypeChanging(value);
					this.SendPropertyChanging();
					this._RelationType = value;
					this.SendPropertyChanged("RelationType");
					this.OnRelationTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateofBirth", DbType="Date NOT NULL")]
		public System.DateTime DateofBirth
		{
			get
			{
				return this._DateofBirth;
			}
			set
			{
				if ((this._DateofBirth != value))
				{
					this.OnDateofBirthChanging(value);
					this.SendPropertyChanging();
					this._DateofBirth = value;
					this.SendPropertyChanged("DateofBirth");
					this.OnDateofBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MemberReg_MemberDetail", Storage="_MemberReg", ThisKey="MemberRegId", OtherKey="MemberRegId", IsForeignKey=true)]
		public MemberReg MemberReg
		{
			get
			{
				return this._MemberReg.Entity;
			}
			set
			{
				MemberReg previousValue = this._MemberReg.Entity;
				if (((previousValue != value) 
							|| (this._MemberReg.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MemberReg.Entity = null;
						previousValue.MemberDetails.Remove(this);
					}
					this._MemberReg.Entity = value;
					if ((value != null))
					{
						value.MemberDetails.Add(this);
						this._MemberRegId = value.MemberRegId;
					}
					else
					{
						this._MemberRegId = default(int);
					}
					this.SendPropertyChanged("MemberReg");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MemberReg")]
	public partial class MemberReg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MemberRegId;
		
		private string _MemberRegNo;
		
		private string _MemberFullName;
		
		private string _MobileNo;
		
		private string _Email;
		
		private byte _Gender;
		
		private int _YearofPassing;
		
		private string _City;
		
		private string _State;
		
		private string _Country;
		
		private string _CurrentProfession;
		
		private string _OrganizationName;
		
		private byte _TshirtSize;
		
		private System.Nullable<decimal> _TotalAmountPaid;
		
		private EntitySet<MemberDetail> _MemberDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMemberRegIdChanging(int value);
    partial void OnMemberRegIdChanged();
    partial void OnMemberRegNoChanging(string value);
    partial void OnMemberRegNoChanged();
    partial void OnMemberFullNameChanging(string value);
    partial void OnMemberFullNameChanged();
    partial void OnMobileNoChanging(string value);
    partial void OnMobileNoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnGenderChanging(byte value);
    partial void OnGenderChanged();
    partial void OnYearofPassingChanging(int value);
    partial void OnYearofPassingChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnCurrentProfessionChanging(string value);
    partial void OnCurrentProfessionChanged();
    partial void OnOrganizationNameChanging(string value);
    partial void OnOrganizationNameChanged();
    partial void OnTshirtSizeChanging(byte value);
    partial void OnTshirtSizeChanged();
    partial void OnTotalAmountPaidChanging(System.Nullable<decimal> value);
    partial void OnTotalAmountPaidChanged();
    #endregion
		
		public MemberReg()
		{
			this._MemberDetails = new EntitySet<MemberDetail>(new Action<MemberDetail>(this.attach_MemberDetails), new Action<MemberDetail>(this.detach_MemberDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberRegId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MemberRegId
		{
			get
			{
				return this._MemberRegId;
			}
			set
			{
				if ((this._MemberRegId != value))
				{
					this.OnMemberRegIdChanging(value);
					this.SendPropertyChanging();
					this._MemberRegId = value;
					this.SendPropertyChanged("MemberRegId");
					this.OnMemberRegIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberRegNo", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MemberRegNo
		{
			get
			{
				return this._MemberRegNo;
			}
			set
			{
				if ((this._MemberRegNo != value))
				{
					this.OnMemberRegNoChanging(value);
					this.SendPropertyChanging();
					this._MemberRegNo = value;
					this.SendPropertyChanged("MemberRegNo");
					this.OnMemberRegNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberFullName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string MemberFullName
		{
			get
			{
				return this._MemberFullName;
			}
			set
			{
				if ((this._MemberFullName != value))
				{
					this.OnMemberFullNameChanging(value);
					this.SendPropertyChanging();
					this._MemberFullName = value;
					this.SendPropertyChanged("MemberFullName");
					this.OnMemberFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string MobileNo
		{
			get
			{
				return this._MobileNo;
			}
			set
			{
				if ((this._MobileNo != value))
				{
					this.OnMobileNoChanging(value);
					this.SendPropertyChanging();
					this._MobileNo = value;
					this.SendPropertyChanged("MobileNo");
					this.OnMobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(350)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="TinyInt NOT NULL")]
		public byte Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearofPassing", DbType="Int NOT NULL")]
		public int YearofPassing
		{
			get
			{
				return this._YearofPassing;
			}
			set
			{
				if ((this._YearofPassing != value))
				{
					this.OnYearofPassingChanging(value);
					this.SendPropertyChanging();
					this._YearofPassing = value;
					this.SendPropertyChanged("YearofPassing");
					this.OnYearofPassingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentProfession", DbType="NVarChar(250)")]
		public string CurrentProfession
		{
			get
			{
				return this._CurrentProfession;
			}
			set
			{
				if ((this._CurrentProfession != value))
				{
					this.OnCurrentProfessionChanging(value);
					this.SendPropertyChanging();
					this._CurrentProfession = value;
					this.SendPropertyChanged("CurrentProfession");
					this.OnCurrentProfessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganizationName", DbType="NVarChar(250)")]
		public string OrganizationName
		{
			get
			{
				return this._OrganizationName;
			}
			set
			{
				if ((this._OrganizationName != value))
				{
					this.OnOrganizationNameChanging(value);
					this.SendPropertyChanging();
					this._OrganizationName = value;
					this.SendPropertyChanged("OrganizationName");
					this.OnOrganizationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TshirtSize", DbType="TinyInt NOT NULL")]
		public byte TshirtSize
		{
			get
			{
				return this._TshirtSize;
			}
			set
			{
				if ((this._TshirtSize != value))
				{
					this.OnTshirtSizeChanging(value);
					this.SendPropertyChanging();
					this._TshirtSize = value;
					this.SendPropertyChanged("TshirtSize");
					this.OnTshirtSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmountPaid", DbType="Money")]
		public System.Nullable<decimal> TotalAmountPaid
		{
			get
			{
				return this._TotalAmountPaid;
			}
			set
			{
				if ((this._TotalAmountPaid != value))
				{
					this.OnTotalAmountPaidChanging(value);
					this.SendPropertyChanging();
					this._TotalAmountPaid = value;
					this.SendPropertyChanged("TotalAmountPaid");
					this.OnTotalAmountPaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MemberReg_MemberDetail", Storage="_MemberDetails", ThisKey="MemberRegId", OtherKey="MemberRegId")]
		public EntitySet<MemberDetail> MemberDetails
		{
			get
			{
				return this._MemberDetails;
			}
			set
			{
				this._MemberDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MemberDetails(MemberDetail entity)
		{
			this.SendPropertyChanging();
			entity.MemberReg = this;
		}
		
		private void detach_MemberDetails(MemberDetail entity)
		{
			this.SendPropertyChanging();
			entity.MemberReg = null;
		}
	}
}
#pragma warning restore 1591
